class Day1 {
  final List<String> title = [
    "DebConf21 Opening",
    "OpenStack Cluster Installer in Bullseye: what's new, what to expect",
    "branch2repo -- enabling casual contributions to debian-installer",
    "బాల స్వేచ్ఛ ప్రాజెక్టు - కంప్యూటర్ ఆధారిత విద్యలో ఒక కొత్త ఒరవడి",
    "Debian Med in Use",
    "Linux's 30th Anniversary",
    "Debian in Retro Computers",
    "Break",
    "GUI vs CLI in Debian",
    "Come and meet the Publicity Team!",
    "Debian Community Team BoF",
    "Resilience in FLOSS: Do founder decisions impact development activity after crisis events?",
    "Local Groups BoF",
    "Break",
    "Calling All FLOSS Founders",
    "Reproducible Buster, Bullseye & Bookworm - where we come from and where we are going",
    "Lenovo + Debian - 2021",
  ];
  final List<String> time = [
    "11:45 - 12:00",
    "12:00 - 12:45",
    "13:00 - 13:45",
    "13:00 - 13:45",
    "14:00 - 14:20",
    "14:30 - 14:50",
    "14:30 - 14:50",
    "14:50 - 16:00",
    "16:00 - 16:20",
    "16:30 - 16:50",
    "17:00 - 17:45",
    "18:00 - 18:45",
    "18:00 - 18:45",
    "18:45 - 20:00",
    "20:00 - 20:45",
    "21:00 - 21:45",
    "22:00 - 22:45",
  ];
  final List<String> speaker = [
    "Nattie Mayer-Hutchings, et al.",
    "Thomas Goirand",
    "Philip Hands",
    "Srichith@reddy25 & satya jonnakuti",
    "Bhanu Prasad Marri & Shiva Prasad Ganji",
    "nickvidal",
    "Kurva Prashanth",
    "",
    "Pavan & Dantu Venkata Sai Kamal",
    "Donald Norwood",
    "Andrew Martin Adrian Cater",
    "Wm Salt Hale",
    "Moray Allan, et al.",
    "",
    "Wm Salt Hale & Kaylea Champion",
    "Holger Levsen",
    "Mark Pearson",
  ];
}
